export const BACKGROUND_COLOR = "#f4f4f4";
export const TEXT_INPUT_BACKGROUND_COLOR = "#d4d4d4";

export enum Color {
  BACKGROUND_COLOR="#292F3F",
  TEXT_COLOR="#FFFFFF",
  BUTTON_BACKGROUND_COLOR="#FFFFFF",
  BUTTON_TEXT_COLOR="#000000",
  PLACEHOLDER_TEXT_COLOR="#D4D4D4"
}
